///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace IntelliSync_BVT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AccountSetting11 recording.
    /// </summary>
    [TestModule("816bc778-6516-409a-9a65-ecdc511e68c7", ModuleType.Recording, 1)]
    public partial class AccountSetting11 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the IntelliSync_BVTRepository repository.
        /// </summary>
        public static IntelliSync_BVTRepository repo = IntelliSync_BVTRepository.Instance;

        static AccountSetting11 instance = new AccountSetting11();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AccountSetting11()
        {
            NewVariable = "testPooll";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AccountSetting11 Instance
        {
            get { return instance; }
        }

#region Variables

        string _NewVariable;

        /// <summary>
        /// Gets or sets the value of variable NewVariable.
        /// </summary>
        [TestVariable("da680b9d-cb9c-4c30-871e-b0e77aca583f")]
        public string NewVariable
        {
            get { return _NewVariable; }
            set { _NewVariable = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.RCTUIImageViewAnimated2' at Center", repo.ComPentairPentairhome.RCTUIImageViewAnimated2Info, new RecordItemIndex(0));
            repo.ComPentairPentairhome.RCTUIImageViewAnimated2.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(1));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome1.EditProfile' at Center", repo.ComPentairPentairhome1.EditProfileInfo, new RecordItemIndex(2));
            repo.ComPentairPentairhome1.EditProfile.Touch();
            Delay.Milliseconds(300);
            
            Report.Snapshot(ReportLevel.Info, "User", "editprofile", repo.ComPentairPentairhome.EditProfileScreenshot, new RecordItemIndex(3));
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'ComPentairPentairhome.RCTSinglelineTextInputView'.", repo.ComPentairPentairhome.RCTSinglelineTextInputViewInfo, new RecordItemIndex(4));
                Validate.Exists(repo.ComPentairPentairhome.RCTSinglelineTextInputViewInfo, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(4)); }
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.backoneditprofile' at Center", repo.ComPentairPentairhome.backoneditprofileInfo, new RecordItemIndex(5));
            repo.ComPentairPentairhome.backoneditprofile.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(6));
            Delay.Duration(10000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
