///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace IntelliSync_BVT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AirSensorProductOveriew recording.
    /// </summary>
    [TestModule("f90423c5-a8f7-4496-a0b6-ec77879067a7", ModuleType.Recording, 1)]
    public partial class AirSensorProductOveriew : ITestModule
    {
        /// <summary>
        /// Holds an instance of the IntelliSync_BVTRepository repository.
        /// </summary>
        public static IntelliSync_BVTRepository repo = IntelliSync_BVTRepository.Instance;

        static AirSensorProductOveriew instance = new AirSensorProductOveriew();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AirSensorProductOveriew()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AirSensorProductOveriew Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(0));
            Delay.Duration(4000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.RCTUIImageViewAnimated1' at Center", repo.ComPentairPentairhome.RCTUIImageViewAnimated1Info, new RecordItemIndex(1));
            repo.ComPentairPentairhome.RCTUIImageViewAnimated1.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.ProductOverview1' at Center", repo.ComPentairPentairhome.ProductOverview1Info, new RecordItemIndex(2));
            repo.ComPentairPentairhome.ProductOverview1.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 6s.", new RecordItemIndex(3));
            Delay.Duration(6000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.ProductOverviewManufacturerPentairNi' at Center", repo.ComPentairPentairhome.ProductOverviewManufacturerPentairNiInfo, new RecordItemIndex(4));
            repo.ComPentairPentairhome.ProductOverviewManufacturerPentairNi.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(5));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.NicknameCOOLSENSOR' at Center", repo.ComPentairPentairhome.NicknameCOOLSENSORInfo, new RecordItemIndex(6));
            repo.ComPentairPentairhome.NicknameCOOLSENSOR.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(7));
            Delay.Duration(5000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "sensornickname", repo.ComPentairPentairhome.NicknameSAVE, false, new RecordItemIndex(8));
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to 'COOL SENSOR' on item 'ComPentairPentairhome.COOLSENSOR2'.", repo.ComPentairPentairhome.COOLSENSOR2Info, new RecordItemIndex(9));
            repo.ComPentairPentairhome.COOLSENSOR2.Element.SetAttributeValue("Text", "COOL SENSOR");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.SAVE2' at Center", repo.ComPentairPentairhome.SAVE2Info, new RecordItemIndex(10));
            repo.ComPentairPentairhome.SAVE2.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(11));
            Delay.Duration(3000, false);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'ComPentairPentairhome.DeviceUpdatedYourProductInformation'.", repo.ComPentairPentairhome.DeviceUpdatedYourProductInformationInfo, new RecordItemIndex(12));
                Validate.Exists(repo.ComPentairPentairhome.DeviceUpdatedYourProductInformationInfo, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(12)); }
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.ContainerOK' at Center", repo.ComPentairPentairhome.ContainerOKInfo, new RecordItemIndex(13));
            repo.ComPentairPentairhome.ContainerOK.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(14));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.RCTView6' at Center", repo.ComPentairPentairhome.RCTView6Info, new RecordItemIndex(15));
            repo.ComPentairPentairhome.RCTView6.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.RCTView9' at Center", repo.ComPentairPentairhome.RCTView9Info, new RecordItemIndex(16));
            repo.ComPentairPentairhome.RCTView9.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(17));
            Delay.Duration(10000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
