///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace IntelliSync_BVT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Home_Dashboard recording.
    /// </summary>
    [TestModule("7ea846cc-394b-4160-8011-bb2710e0d030", ModuleType.Recording, 1)]
    public partial class Home_Dashboard : ITestModule
    {
        /// <summary>
        /// Holds an instance of the IntelliSync_BVTRepository repository.
        /// </summary>
        public static IntelliSync_BVTRepository repo = IntelliSync_BVTRepository.Instance;

        static Home_Dashboard instance = new Home_Dashboard();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Home_Dashboard()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Home_Dashboard Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'ComPentairPentairhome.ProblemDetected1AlertYourIntellisyn'.", repo.ComPentairPentairhome.ProblemDetected1AlertYourIntellisynInfo, new RecordItemIndex(0));
                Validate.Exists(repo.ComPentairPentairhome.ProblemDetected1AlertYourIntellisynInfo, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.AssetsSrcCommonFeatureImagesNotific' at Center", repo.ComPentairPentairhome.AssetsSrcCommonFeatureImagesNotificInfo, new RecordItemIndex(1));
            repo.ComPentairPentairhome.AssetsSrcCommonFeatureImagesNotific.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.Recent' at Center", repo.ComPentairPentairhome.RecentInfo, new RecordItemIndex(2));
            repo.ComPentairPentairhome.Recent.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.Severity1' at Center", repo.ComPentairPentairhome.Severity1Info, new RecordItemIndex(3));
            repo.ComPentairPentairhome.Severity1.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.RCTView' at Center", repo.ComPentairPentairhome.RCTViewInfo, new RecordItemIndex(4));
            repo.ComPentairPentairhome.RCTView.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(5));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.EditDashboard1' at Center", repo.ComPentairPentairhome.EditDashboard1Info, new RecordItemIndex(6));
            repo.ComPentairPentairhome.EditDashboard1.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(7));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.AssetsSrcCommonFeatureImagesDeviceA' at Center", repo.ComPentairPentairhome.AssetsSrcCommonFeatureImagesDeviceAInfo, new RecordItemIndex(8));
            repo.ComPentairPentairhome.AssetsSrcCommonFeatureImagesDeviceA.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(9));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.AssetsSrcCommonFeatureImagesNpHome1' at Center", repo.ComPentairPentairhome.AssetsSrcCommonFeatureImagesNpHome1Info, new RecordItemIndex(10));
            repo.ComPentairPentairhome.AssetsSrcCommonFeatureImagesNpHome1.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(11));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome1.AssetsSrcCommonFeatureImagesTimerTa' at Center", repo.ComPentairPentairhome1.AssetsSrcCommonFeatureImagesTimerTaInfo, new RecordItemIndex(12));
            repo.ComPentairPentairhome1.AssetsSrcCommonFeatureImagesTimerTa.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(13));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome1.HomeButton' at Center", repo.ComPentairPentairhome1.HomeButtonInfo, new RecordItemIndex(14));
            repo.ComPentairPentairhome1.HomeButton.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(15));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.AccountSetting1' at Center", repo.ComPentairPentairhome.AccountSetting1Info, new RecordItemIndex(16));
            repo.ComPentairPentairhome.AccountSetting1.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome1.HomeButton' at Center", repo.ComPentairPentairhome1.HomeButtonInfo, new RecordItemIndex(17));
            repo.ComPentairPentairhome1.HomeButton.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(18));
            Delay.Duration(10000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
