///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace IntelliSync_BVT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The IntelliSyncSettingandProductOverview recording.
    /// </summary>
    [TestModule("cbdd9131-f750-4538-9431-5a76c977f7fe", ModuleType.Recording, 1)]
    public partial class IntelliSyncSettingandProductOverview : ITestModule
    {
        /// <summary>
        /// Holds an instance of the IntelliSync_BVTRepository repository.
        /// </summary>
        public static IntelliSync_BVTRepository repo = IntelliSync_BVTRepository.Instance;

        static IntelliSyncSettingandProductOverview instance = new IntelliSyncSettingandProductOverview();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public IntelliSyncSettingandProductOverview()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static IntelliSyncSettingandProductOverview Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                Report.Log(ReportLevel.Info, "Touch", "(Optional Action)\r\nTouch item 'ComPentairPentairhome.RCTUIImageViewAnimated1' at Center", repo.ComPentairPentairhome.RCTUIImageViewAnimated1Info, new RecordItemIndex(0));
                repo.ComPentairPentairhome.RCTUIImageViewAnimated1.Touch();
                Delay.Milliseconds(300);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
            try {
                Report.Log(ReportLevel.Info, "Delay", "(Optional Action)\r\nWaiting for 1s.", new RecordItemIndex(1));
                Delay.Duration(1000, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
            try {
                Report.Screenshot(ReportLevel.Info, "User", "IntelliSyncSetting", repo.ComPentairPentairhome.INTELLISYNCRDProductOverviewNotificat, false, new RecordItemIndex(2));
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(3));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.ProductOverview' at Center", repo.ComPentairPentairhome.ProductOverviewInfo, new RecordItemIndex(4));
            repo.ComPentairPentairhome.ProductOverview.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(5));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ComPentairPentairhome.DeviceIDPNR04ESC100002808A'.", repo.ComPentairPentairhome.DeviceIDPNR04ESC100002808AInfo, new RecordItemIndex(6));
            Validate.Exists(repo.ComPentairPentairhome.DeviceIDPNR04ESC100002808AInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Up (270°)' starting from 'Center' with distance '250' with swipe duration'800ms' and step count '0' on item 'ComPentairPentairhome.Nickname'.", repo.ComPentairPentairhome.NicknameInfo, new RecordItemIndex(7));
            repo.ComPentairPentairhome.Nickname.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Up (270°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "250"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "800ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.INTELLISYNCRD1' at Center", repo.ComPentairPentairhome.INTELLISYNCRD1Info, new RecordItemIndex(8));
            repo.ComPentairPentairhome.INTELLISYNCRD1.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(9));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to 'INTELLISYNCRHOME' on item 'ComPentairPentairhome.COOLSENSOR2'.", repo.ComPentairPentairhome.COOLSENSOR2Info, new RecordItemIndex(10));
            repo.ComPentairPentairhome.COOLSENSOR2.Element.SetAttributeValue("Text", "INTELLISYNCRHOME");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.SAVE1' at Center", repo.ComPentairPentairhome.SAVE1Info, new RecordItemIndex(11));
            repo.ComPentairPentairhome.SAVE1.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(12));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.ContainerOK' at Center", repo.ComPentairPentairhome.ContainerOKInfo, new RecordItemIndex(13));
            repo.ComPentairPentairhome.ContainerOK.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(14));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Up (270°)' starting from 'Center' with distance '100' with swipe duration'800ms' and step count '0' on item 'ComPentairPentairhome.Nickname1'.", repo.ComPentairPentairhome.Nickname1Info, new RecordItemIndex(15));
            repo.ComPentairPentairhome.Nickname1.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Up (270°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "100"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "800ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.Address250HartfordAveBellingham' at Center", repo.ComPentairPentairhome.Address250HartfordAveBellinghamInfo, new RecordItemIndex(16));
            repo.ComPentairPentairhome.Address250HartfordAveBellingham.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(17));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome1.AssetsSrcCommonFeatureImagesArrowDo' at Center", repo.ComPentairPentairhome1.AssetsSrcCommonFeatureImagesArrowDoInfo, new RecordItemIndex(18));
            repo.ComPentairPentairhome1.AssetsSrcCommonFeatureImagesArrowDo.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.Container53DiamondStSanFrancisco' at Center", repo.ComPentairPentairhome.Container53DiamondStSanFranciscoInfo, new RecordItemIndex(19));
            repo.ComPentairPentairhome.Container53DiamondStSanFrancisco.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(20));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ShalinisIPhone.Save' at Center", repo.ShalinisIPhone.SaveInfo, new RecordItemIndex(21));
            repo.ShalinisIPhone.Save.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(22));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.TextOK' at Center", repo.ComPentairPentairhome.TextOKInfo, new RecordItemIndex(23));
            repo.ComPentairPentairhome.TextOK.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(24));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.RCTView6' at Center", repo.ComPentairPentairhome.RCTView6Info, new RecordItemIndex(25));
            repo.ComPentairPentairhome.RCTView6.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(26));
            Delay.Duration(5000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
