///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace IntelliSync_BVT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Walkthroughh recording.
    /// </summary>
    [TestModule("22ec7804-99d7-4f81-8118-16a10bdbdbc4", ModuleType.Recording, 1)]
    public partial class Walkthroughh : ITestModule
    {
        /// <summary>
        /// Holds an instance of the IntelliSync_BVTRepository repository.
        /// </summary>
        public static IntelliSync_BVTRepository repo = IntelliSync_BVTRepository.Instance;

        static Walkthroughh instance = new Walkthroughh();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Walkthroughh()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Walkthroughh Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Screenshot(ReportLevel.Success, "User", "Walkthrogh screen_1 captured successfully", repo.ComPentairPentairhome.Main_window, false, new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.NEXT' at Center", repo.ComPentairPentairhome.NEXTInfo, new RecordItemIndex(1));
            repo.ComPentairPentairhome.NEXT.Touch();
            Delay.Milliseconds(300);
            
            Report.Screenshot(ReportLevel.Success, "User", "Walkthrogh screen_2 captured successfully", repo.ComPentairPentairhome.Main_window, false, new RecordItemIndex(2));
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.NEXT' at Center", repo.ComPentairPentairhome.NEXTInfo, new RecordItemIndex(3));
            repo.ComPentairPentairhome.NEXT.Touch();
            Delay.Milliseconds(300);
            
            Report.Screenshot(ReportLevel.Success, "User", "Walkthrogh screen_3 captured successfully", repo.ComPentairPentairhome.Main_window, false, new RecordItemIndex(4));
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.NEXT' at Center", repo.ComPentairPentairhome.NEXTInfo, new RecordItemIndex(5));
            repo.ComPentairPentairhome.NEXT.Touch();
            Delay.Milliseconds(300);
            
            Report.Screenshot(ReportLevel.Success, "User", "Walkthrogh screen_4 captured successfully", repo.ComPentairPentairhome.Main_window, false, new RecordItemIndex(6));
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.NEXT' at Center", repo.ComPentairPentairhome.NEXTInfo, new RecordItemIndex(7));
            repo.ComPentairPentairhome.NEXT.Touch();
            Delay.Milliseconds(300);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
